# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 748d4d73f903c9e29f35f2e152485e39d43911d47c3bcd48f984d129678dd49ac46503e5146f3dfe88164f203a61ae94e178155a773cb8140e348cdad75317d8

test:
  secret_key_base: cce754440516d9aee4cc6769fa9b376ad1918045a2f40b0f9a5682e9db5bf9355406a40e112b34caf5bc619eaf55b1416b1ffdd5de61a47d7212b5ffcc00d78f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
